CREATE TABLE `ates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`teacherName` varchar(255) NOT NULL,
	`institution` varchar(255) NOT NULL,
	`ateName` varchar(255) NOT NULL,
	`grade` varchar(50),
	`competencia` varchar(255),
	`tipo` enum('producto','proceso','sistema') NOT NULL DEFAULT 'producto',
	`fase1Problema` text,
	`fase1Contexto` text,
	`fase1PreguntaOrientadora` text,
	`fase1Importancia` text,
	`fase1Completed` int NOT NULL DEFAULT 0,
	`fase2Investigacion` text,
	`fase2Ideas` text,
	`fase2MejorIdea` text,
	`fase2Justificacion` text,
	`fase2Completed` int NOT NULL DEFAULT 0,
	`fase3DescripcionSolucion` text,
	`fase3CriteriosDiseño` text,
	`fase3Materiales` text,
	`fase3Herramientas` text,
	`fase3Esquema` text,
	`fase3Completed` int NOT NULL DEFAULT 0,
	`fase4Planificacion` text,
	`fase4Pasos` text,
	`fase4Cronograma` text,
	`fase4Responsables` text,
	`fase4Desafios` text,
	`fase4Avances` text,
	`fase4Completed` int NOT NULL DEFAULT 0,
	`fase5Funcionamiento` text,
	`fase5ErroresEncontrados` text,
	`fase5Mejoras` text,
	`fase5Resultados` text,
	`fase5CriteriosEvaluacion` text,
	`fase5Completed` int NOT NULL DEFAULT 0,
	`fase6DescripcionFinal` text,
	`fase6AudienciaDestino` text,
	`fase6FormatoPresentacion` text,
	`fase6MensajePrincipal` text,
	`fase6Aprendizajes` text,
	`fase6Impacto` text,
	`fase6Completed` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `ates` ADD CONSTRAINT `ates_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;