export const PHASES = [
  {
    number: 1,
    title: "Identificación del problema",
    icon: "🔍",
    color: "#3B82F6",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    tip: "Asegúrate de que el problema sea específico, observable y relevante para tus estudiantes.",
    fields: [
      { key: "fase1Problema", label: "Descripción del Problema", required: true, type: "textarea" },
      { key: "fase1Contexto", label: "Contexto", required: true, type: "textarea" },
      { key: "fase1PreguntaOrientadora", label: "Pregunta Orientadora", required: true, type: "input" },
      { key: "fase1Importancia", label: "¿Por qué es importante?", required: true, type: "textarea" },
    ],
  },
  {
    number: 2,
    title: "Exploración y documentación",
    icon: "📚",
    color: "#8B5CF6",
    bg: "#F5F3FF",
    border: "#DDD6FE",
    tip: "Investiga el problema profundamente antes de proponer soluciones.",
    fields: [
      { key: "fase2Investigacion", label: "Investigación Realizada", required: true, type: "textarea" },
      { key: "fase2Ideas", label: "Ideas de Solución (una por línea)", required: false, type: "textarea" },
      { key: "fase2MejorIdea", label: "Mejor Idea Seleccionada", required: true, type: "input" },
      { key: "fase2Justificacion", label: "Justificación de la Elección", required: true, type: "textarea" },
    ],
  },
  {
    number: 3,
    title: "Diseño de la solución",
    icon: "✏️",
    color: "#10B981",
    bg: "#F0FDF4",
    border: "#A7F3D0",
    tip: "Sé específico con las medidas y cantidades. Esto facilitará la construcción del prototipo.",
    fields: [
      { key: "fase3DescripcionSolucion", label: "Descripción Detallada de la Solución", required: true, type: "textarea" },
      { key: "fase3CriteriosDiseño", label: "Criterios de Diseño", required: true, type: "textarea" },
      { key: "fase3Materiales", label: "Materiales Necesarios", required: true, type: "textarea" },
      { key: "fase3Herramientas", label: "Herramientas Necesarias", required: true, type: "textarea" },
      { key: "fase3Esquema", label: "Esquema o Boceto (descripción)", required: false, type: "textarea" },
    ],
  },
  {
    number: 4,
    title: "Planeación y construcción",
    icon: "🔧",
    color: "#F59E0B",
    bg: "#FFFBEB",
    border: "#FDE68A",
    tip: "Documenta los avances y desafíos durante la construcción para aprender de ellos.",
    fields: [
      { key: "fase4Planificacion", label: "Plan de Construcción", required: true, type: "textarea" },
      { key: "fase4Pasos", label: "Pasos de Construcción (numerados)", required: true, type: "textarea" },
      { key: "fase4Cronograma", label: "Cronograma", required: true, type: "textarea" },
      { key: "fase4Responsables", label: "Responsables y Roles", required: true, type: "textarea" },
      { key: "fase4Desafios", label: "Desafíos Encontrados", required: false, type: "textarea" },
      { key: "fase4Avances", label: "Registro de Avances", required: false, type: "textarea" },
    ],
  },
  {
    number: 5,
    title: "Evaluación y mejora",
    icon: "📊",
    color: "#EF4444",
    bg: "#FFF5F5",
    border: "#FCA5A5",
    tip: "La evaluación honesta y las mejoras propuestas son clave para un proyecto exitoso.",
    fields: [
      { key: "fase5Funcionamiento", label: "¿Cómo funcionó el prototipo?", required: true, type: "textarea" },
      { key: "fase5ErroresEncontrados", label: "Errores o Problemas Encontrados", required: true, type: "textarea" },
      { key: "fase5Mejoras", label: "Mejoras Propuestas", required: true, type: "textarea" },
      { key: "fase5Resultados", label: "Resultados Obtenidos", required: true, type: "textarea" },
      { key: "fase5CriteriosEvaluacion", label: "Criterios de Evaluación", required: false, type: "textarea" },
    ],
  },
  {
    number: 6,
    title: "Comunicación y socialización",
    icon: "🎤",
    color: "#6366F1",
    bg: "#EEF2FF",
    border: "#C7D2FE",
    tip: "Comparte tu proyecto con entusiasmo. Tu trabajo puede inspirar a otros.",
    fields: [
      { key: "fase6DescripcionFinal", label: "Descripción Final del Proyecto", required: true, type: "textarea" },
      { key: "fase6AudienciaDestino", label: "Audiencia Destino", required: true, type: "textarea" },
      { key: "fase6FormatoPresentacion", label: "Formato de Presentación", required: true, type: "input" },
      { key: "fase6MensajePrincipal", label: "Mensaje Principal", required: true, type: "textarea" },
      { key: "fase6Aprendizajes", label: "Aprendizajes Obtenidos", required: true, type: "textarea" },
      { key: "fase6Impacto", label: "Impacto en la Comunidad", required: false, type: "textarea" },
    ],
  },
];

export const COMPONENTES_TECNOLOGICOS = [
  "Naturaleza y Evolución de la T&I",
  "Uso y apropiación de la T&I",
  "Solución de problemas con T&I",
  "Tecnología, Informática y Sociedad",
];
